// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGL3Cq5dRHATX2osv_zr-1NNBS6c1ni6c',
    appId: '1:438514154136:web:561940685d18f051b4eeed',
    messagingSenderId: '438514154136',
    projectId: 'shop-ef031',
    authDomain: 'shop-ef031.firebaseapp.com',
    storageBucket: 'shop-ef031.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr8ODZF6W6ZmdxeQg2IsV1Xd6EvaIFefo',
    appId: '1:438514154136:android:054944ca12ecd416b4eeed',
    messagingSenderId: '438514154136',
    projectId: 'shop-ef031',
    storageBucket: 'shop-ef031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANFm8LHwq-bUAqcNU8TQOXPbxAfeuls-k',
    appId: '1:438514154136:ios:17bda4020508f801b4eeed',
    messagingSenderId: '438514154136',
    projectId: 'shop-ef031',
    storageBucket: 'shop-ef031.firebasestorage.app',
    androidClientId: '438514154136-t8cs1ol21d6n1vkpjj9hr2c6nm513hbm.apps.googleusercontent.com',
    iosClientId: '438514154136-c3ijkn10gp0e74cipljlubd30n8nqtjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop',
  );

}